=== rubydhash/games-concursos/games/src/main/resources/arquivos/conteudos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.gamesconcursos.com.br/conteudos" xmlns="http://www.gamesconcursos.com.br/conteudos"
	elementFormDefault="qualified">

	<xs:element name="conteudosRoot">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="conteudos">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="conteudo" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="codigo" type="xs:integer" />
										<xs:element name="sigla" type="xs:string" />
										<xs:element name="nome" type="xs:string" />
										<xs:element name="nomeOriginal" type="xs:string" />
										<xs:element name="descricao" type="xs:string" />
										<xs:element name="tituloHorizontal" type="xs:string" />
										<xs:element name="tituloVertical" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== rubydhash/games-concursos/games/src/main/resources/arquivos/cmmi-v1.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<conteudosRoot xmlns="http://www.gamesconcursos.com.br/conteudos"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gamesconcursos.com.br/conteudos conteudos.xsd">
	<conteudos>
		<conteudo>
			<codigo>0</codigo>
			<sigla>sigla</sigla>
			<nome>nome</nome>
			<nomeOriginal>nomeOriginal</nomeOriginal>
			<descricao>descricao</descricao>
			<tituloHorizontal>tituloHorizontal</tituloHorizontal>
			<tituloVertical>tituloVertical</tituloVertical>
		</conteudo>
		<conteudo>
			<codigo>1</codigo>
			<sigla>sigla</sigla>
			<nome>nome</nome>
			<nomeOriginal>nomeOriginal</nomeOriginal>
			<descricao>descricao</descricao>
			<tituloHorizontal>tituloHorizontal</tituloHorizontal>
			<tituloVertical>tituloVertical</tituloVertical>
		</conteudo>
		<conteudo>
			<codigo>2</codigo>
			<sigla>sigla</sigla>
			<nome>nome</nome>
			<nomeOriginal>nomeOriginal</nomeOriginal>
			<descricao>descricao</descricao>
			<tituloHorizontal>tituloHorizontal</tituloHorizontal>
			<tituloVertical>tituloVertical</tituloVertical>
		</conteudo>
	</conteudos>
</conteudosRoot>
